name: Deploy to FTP
on:
  push:
    branches: [ main, server ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./cms/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env
          .github/**
          README.md